<?php
/**
 * @file
 * A simple module to create a Drupal Block programmatically,
 * which then can be placed within any region using the block system.
 * Created by:  Prof. James Barnett, Babson College 2013.
 */

function angular2RouterInDrupal_block_info() {
    // This example comes from node.module.
    $blocks['angular2routerblock'] = array(
        'info' => t('HMS Angular 2 Router Block'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function angular2RouterInDrupal_block_view($delta = '') {
    // This example is adapted from node.module.
    $block = array();
    switch ($delta) {
        case 'angular2routerblock':
            /*$result = db_query("select n.title, u.uid, n.created from node n,
                               users u where u.uid = n.uid order by n.created desc limit 5");
            $content = "";
            foreach($result as $row){
              $content .= $row->title . '</br>';
            }*/
            $output =  array(
                'first_para' => array(
                    '#type' => 'markup',
                    '#markup' => '
<simple-routing></simple-routing>',
                    '#attached' => array(
                        'js' => array(
                            'sites/all/modules/custom/angular2RouterInDrupal/js/angular2-polyfills.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/system.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/typescript.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/Rx.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/angular2.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/router.js',
                            'sites/all/modules/custom/angular2RouterInDrupal/js/angular2RouterInDrupal.js'
                        ),
                        'css' => array(
                            'sites/all/modules/custom/angular2RouterInDrupal/css/angular2RouterInDrupal.css',
                        )
                    ),
                )
            );

            $block['subject'] = t('HMS Angular 2 Basic Router Block');
            $block['content'] = $output;
            break;
    }
    return $block;
}