<?php
require_once "dropbox-sdk/Dropbox/autoload.php";
use \Dropbox as dbx;

/**
 * @file
 * A simple module to create a Drupal Block programmatically,
 * which then can be placed within any region using the block system.
 * Created by:  Prof. James Barnett, Babson College 2013.
 */

function groupdropbox_menu() {
  $items = array();
  $items['groupdropbox-groupbox-json'] = array(
    'title' => 'A basic Drupal page serving up json from a dropbox user account',
    'page callback' => 'groupdropbox_groupbox_json',
    'access arguments' => array('access content'),
  );
  return $items;
}

function groupdropbox_groupbox_json() {
/*$myItems = '[
  {"name":"Jonny","age":20},
  {"name":"John","age":22},
  {"name":"Jonathan Gouldesohn","age":24},
  {"name":"Jonathan Tasty","age":28}
]';
$myItems = json_decode($myItems);
watchdog('groupdropbox', '<pre>' . print_r($myItems, TRUE) . '</pre>');*/
$accessToken = "a_2MdW8-dTYAAAAAAAAvU2gyKwjAJ_M5fxC8PHHDfrflsii6Rc77TFgFFfG2ixpG";
$dbxClient = new dbx\Client($accessToken, "PHP-Example/1.0");
$accountInfo = $dbxClient->getAccountInfo();

$folderMetadata = $dbxClient->getMetadataWithChildren("/");
watchdog('groupdropbox', '<pre>' . print_r($folderMetadata['contents'], TRUE) . '</pre>');
$linkToShare = $dbxClient->createShareableLink("/working-draft.txt");
watchdog('grouplinktoshare', '<pre>' . print_r($linkToShare, TRUE) . '</pre>');
fclose($f);

drupal_json_output($folderMetadata['contents']);

}

function groupdropbox_block_info() {
    // This example comes from node.module.
    $blocks['groupdropbox'] = array(
        'info' => t('Group Drop Box'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function groupdropbox_block_view($delta = '') {
    // This example is adapted from node.module.
    $block = array();
    switch ($delta) {
        case 'groupdropbox':
            $output =  array(
                'first_para' => array(
                    '#type' => 'markup',
                    '#markup' => '
<simple-routing></simple-routing>',
                    '#attached' => array(
                        'js' => array(
                            'sites/all/modules/custom/groupdropbox/js/angular2-polyfills.js',
                            'sites/all/modules/custom/groupdropbox/js/system.js',
                            'sites/all/modules/custom/groupdropbox/js/typescript.js',
                            'sites/all/modules/custom/groupdropbox/js/Rx.js',
                            'sites/all/modules/custom/groupdropbox/js/angular2.js',
			    'sites/all/modules/custom/groupdropbox/js/router.dev.js',
			    'sites/all/modules/custom/groupdropbox/js/http.dev.js',
                            'sites/all/modules/custom/groupdropbox/js/groupdropbox.js'
                        ),
                        'css' => array(
                            'sites/all/modules/custom/groupdropbox/css/groupdropbox.css',
                        )
                    ),
                )
            );

            $block['subject'] = t('HMS Angular 2 Router Block');
            $block['content'] = $output;
            break;
    }
    return $block;
}
